spring:
  application:
  name: event-sourcing

springdoc:
  swagger-ui:
    path: /api-documentation
    validatorUrl: none
    disable-swagger-default-url: true
  api-docs:
    path: /api-documentation-json